test_that("cv.rsv runs on binary outcome data", {
  dat <- sim_rsv_data(n_e = 200, n_o = 400, tau = 0.10, seed = 42)
  R   <- as.matrix(dat[, paste0("R", 1:5)])

  fit <- cv.rsv(
    Y        = dat$Y,
    D        = dat$D,
    S_e      = dat$S_e,
    S_o      = dat$S_o,
    R        = R,
    y_levels = c(0L, 1L),
    yK       = 0L,
    models   = list(
      Y   = list(model = "logit"),
      D   = list(model = "logit"),
      S_e = list(model = "logit"),
      S_o = list(model = "logit")
    ),
    nfolds = 2,
    seed   = 1
  )

  expect_s3_class(fit, "cv.rsv")
  expect_true(is.numeric(fit$coefficients))
  expect_length(fit$coefficients, 1)
  expect_true(is.finite(fit$coefficients))
  expect_equal(fit$n.exp, 200)
  expect_equal(fit$n.obs, 400)
})

test_that("cv.rsv relevance is finite and positive", {
  dat <- sim_rsv_data(n_e = 200, n_o = 400, tau = 0.10, seed = 5)
  R   <- as.matrix(dat[, paste0("R", 1:5)])

  fit <- cv.rsv(
    Y        = dat$Y,
    D        = dat$D,
    S_e      = dat$S_e,
    S_o      = dat$S_o,
    R        = R,
    y_levels = c(0L, 1L),
    yK       = 0L,
    models   = list(
      Y   = list(model = "logit"),
      D   = list(model = "logit"),
      S_e = list(model = "logit"),
      S_o = list(model = "logit")
    ),
    nfolds = 2,
    seed   = 2
  )

  expect_true(is.finite(fit$relevance))
  expect_gt(fit$relevance, 0)
})

test_that("add_se with influence returns finite SE", {
  dat <- sim_rsv_data(n_e = 200, n_o = 400, tau = 0.10, seed = 10)
  R   <- as.matrix(dat[, paste0("R", 1:5)])

  fit <- cv.rsv(
    Y        = dat$Y,
    D        = dat$D,
    S_e      = dat$S_e,
    S_o      = dat$S_o,
    R        = R,
    y_levels = c(0L, 1L),
    yK       = 0L,
    models   = list(
      Y   = list(model = "logit"),
      D   = list(model = "logit"),
      S_e = list(model = "logit"),
      S_o = list(model = "logit")
    ),
    nfolds = 2,
    seed   = 3
  )

  fit_se <- add_se(fit, method = "influence")

  expect_true(is.finite(fit_se$se))
  expect_gt(fit_se$se, 0)
  expect_true(is.finite(fit_se$cond_J))
})

test_that("add_se with score_bootstrap returns finite SE", {
  dat <- sim_rsv_data(n_e = 200, n_o = 400, tau = 0.10, seed = 20)
  R   <- as.matrix(dat[, paste0("R", 1:5)])

  fit <- cv.rsv(
    Y        = dat$Y,
    D        = dat$D,
    S_e      = dat$S_e,
    S_o      = dat$S_o,
    R        = R,
    y_levels = c(0L, 1L),
    yK       = 0L,
    models   = list(
      Y   = list(model = "logit"),
      D   = list(model = "logit"),
      S_e = list(model = "logit"),
      S_o = list(model = "logit")
    ),
    nfolds = 2,
    seed   = 4
  )

  fit_se <- add_se(fit, method = "score_bootstrap", B = 25, num.threads = 1)

  expect_true(is.finite(fit_se$se))
  expect_gt(fit_se$se, 0)
  # kappa diagnostics exist as numeric fields; may be NA if J is ill-conditioned
  expect_true(is.numeric(fit_se$cond_J_median))
  expect_true(is.numeric(fit_se$cond_J_max))
})

test_that("cv.rsv estimate is in plausible range for tau=0.10", {
  # With n=600 the estimate should be within +/- 0.20 of the truth (loose check)
  dat <- sim_rsv_data(n_e = 300, n_o = 700, tau = 0.10, seed = 77)
  R   <- as.matrix(dat[, paste0("R", 1:5)])

  fit <- cv.rsv(
    Y        = dat$Y,
    D        = dat$D,
    S_e      = dat$S_e,
    S_o      = dat$S_o,
    R        = R,
    y_levels = c(0L, 1L),
    yK       = 0L,
    models   = list(
      Y   = list(model = "logit"),
      D   = list(model = "logit"),
      S_e = list(model = "logit"),
      S_o = list(model = "logit")
    ),
    nfolds = 2,
    seed   = 5
  )

  expect_lt(abs(fit$coefficients - 0.10), 0.20)
})

test_that("rsv_example generator produces expected structure", {
  # The bundled rsv_example is generated by sim_rsv_data() with these args;
  # this test verifies the generator is stable.
  dat <- sim_rsv_data(n_e = 300, n_o = 700, tau = 0.10, p0 = 0.30,
                      n_r = 5, seed = 42)

  expect_s3_class(dat, "data.frame")
  expect_equal(nrow(dat), 1000)
  expect_named(dat, c("Y", "D", "S_e", "S_o", "R1", "R2", "R3", "R4", "R5"))
  expect_true(all(na.omit(dat$Y) %in% c(0L, 1L)))
})
